# -*- coding: utf-8 -*-
"""TECHAPP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMvMekO7_JYTrpws6fbXp9s8ipDqjzty
"""

!pip install streamlit

import streamlit as st
import joblib
import numpy as np

# ========== Load the Model ==========
model = joblib.load("gadget_classifier_model.pkl")

# ========== Streamlit Page Settings ==========
st.set_page_config(page_title="🧠 Tech Gadget Purchase Predictor", layout="centered")

# ========== Custom CSS for Styling ==========
st.markdown("""
    <style>
        .main {
            background-color: #0f1117;
            color: #ffffff;
            padding: 2rem;
        }
        .stButton > button {
            background-color: #4CAF50;
            color: white;
            border-radius: 8px;
            font-size: 18px;
            padding: 0.6em 1.5em;
        }
        .title {
            text-align: center;
            font-size: 36px;
            color: #00FFAA;
            font-weight: 800;
        }
        .subtitle {
            text-align: center;
            font-size: 20px;
            color: #999;
        }
        .result {
            font-size: 26px;
            font-weight: bold;
            text-align: center;
            padding: 1rem;
            border-radius: 12px;
        }
    </style>
""", unsafe_allow_html=True)

# ========== Title ==========
st.markdown("<div class='title'>🤖 Gadget Buyer Prediction App</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Will someone buy the next big tech gadget? Let’s find out!</div>", unsafe_allow_html=True)
st.markdown("---")

# ========== User Input ==========
col1, col2 = st.columns(2)

with col1:
    age_group = st.selectbox("👤 Age Group", [0, 1, 2, 3, 4, 5], format_func=lambda x: [
        "<18", "18–24", "25–34", "35–44", "45–54", "55+"][x])

    tech_interest = st.slider("💡 Tech Interest Level", 1, 5, 3)

    past_purchase = st.selectbox("🛒 Past Gadget Buying Behavior", [0, 1, 2, 3], format_func=lambda x: [
        "Never", "Rarely", "Occasionally", "Often"][x])

with col2:
    monthly_income = st.number_input("💸 Monthly Income (₹)", min_value=0.0, step=1000.0)

    social_engagement = st.slider("📱 Tech Engagement on Social Media", 1, 5, 3)

# ========== Predict ==========
st.markdown("### 🧪 Click to Predict")

if st.button("🔍 Predict Now"):
    user_data = np.array([[age_group, tech_interest, past_purchase, monthly_income, social_engagement]])
    prediction = model.predict(user_data)[0]

    if prediction == 1:
        st.markdown("<div class='result' style='background-color:#008080;'>✅ This person is **LIKELY TO BUY** the gadget.</div>", unsafe_allow_html=True)
    else:
        st.markdown("<div class='result' style='background-color:#800000;'>❌ This person is **NOT LIKELY TO BUY** the gadget.</div>", unsafe_allow_html=True)

# ========== Footer ==========
st.markdown("---")
st.markdown("<p style='text-align:center; color:gray;'>Created with ❤️ using Streamlit</p>", unsafe_allow_html=True)